version: 2

jobs:
  build:
    docker:
      # I'll have to update this every now and then
      # https://circleci.com/docs/2.0/circleci-images/#nodejs
      - image: circleci/node:9.9

    branches:
      only:
        - master

    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm i -D
      - run: npm t
      - run: npm publish
