version: 2

jobs:
  build:
    docker:
      - image: circleci/node:7.5.0

    branches:
      only:
        - master

    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm install --only=dev
      - run: npm t
      - run: npm publish
